name: Change README
on: 
  workflow_dispatch:

jobs:
  build:
    name: (Auto) Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Modify README file
        run: echo -e "text\n" >> README.md
      - name: Setup git config
        run: |
          git config user.name "Sephora Bot"
          git config user.email "devops+gh-sephora-bot@sephoradigital.com"
      - uses: stefanzweifel/git-auto-commit-action@v4